In [194]:
import pandas as pd

In [195]:
df=pd.read_csv("covid_toy.csv")

In [196]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [197]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [198]:
# seperate input and output variable
x=df[["age","gender","fever","cough","city"]]
y=df[["has_covid"]]

In [199]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2
)

In [200]:
x_train

    age  gender  fever   cough       city
92   82  Female  102.0  Strong    Kolkata
76   80    Male  100.0    Mild  Bangalore
7    20  Female    NaN  Strong     Mumbai
69   73  Female  103.0    Mild      Delhi
65   69  Female  102.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
51   11  Female  100.0  Strong    Kolkata
77    8  Female  101.0    Mild    Kolkata
6    14    Male  101.0  Strong  Bangalore
21   73    Male   98.0    Mild  Bangalore
22   71  Female   98.0  Strong    Kolkata

[80 rows x 5 columns]

In [201]:
x_test

    age  gender  fever   cough       city
42   27    Male  100.0    Mild      Delhi
41   82    Male    NaN    Mild    Kolkata
87   47    Male  101.0  Strong  Bangalore
52   47  Female  100.0  Strong  Bangalore
5    84  Female    NaN    Mild  Bangalore
56   71    Male    NaN  Strong    Kolkata
53   83    Male   98.0    Mild      Delhi
20   12    Male   98.0  Strong  Bangalore
54   60  Female   99.0    Mild     Mumbai
23   80  Female   98.0    Mild      Delhi
33   26  Female   98.0    Mild    Kolkata
36   38  Female  101.0    Mild  Bangalore
24   13  Female  100.0  Strong    Kolkata
9    64  Female  101.0    Mild      Delhi
1    27    Male  100.0    Mild      Delhi
61   81  Female   98.0  Strong     Mumbai
97   20  Female  101.0    Mild  Bangalore
2    42    Male  101.0    Mild      Delhi
17   40  Female   98.0  Strong      Delhi
85   16  Female  103.0    Mild  Bangalore

In [202]:
#column tranformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder,OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(
    transformers=[
    ("scaler",StandardScaler(),["age"]),
    ("SimpleImputer",SimpleImputer(strategy="most_frequent"),["fever"]),
    ("OneHot",OneHotEncoder(drop="first",sparse_output=False),["gender","city"]),
    ("Ordinal",OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"])
    ],
    remainder="passthrough"
)

In [203]:
x_train_new=transformer.fit_transform(x_train)

In [204]:
x_train_new=pd.DataFrame(x_train_new)

In [205]:
x_train_new

           0      1    2    3    4    5    6
0   1.575960  102.0  0.0  0.0  1.0  0.0  1.0
1   1.494567  100.0  1.0  0.0  0.0  0.0  0.0
2  -0.947204  104.0  0.0  0.0  0.0  1.0  1.0
3   1.209694  103.0  0.0  1.0  0.0  0.0  0.0
4   1.046909  102.0  0.0  0.0  0.0  0.0  0.0
..       ...    ...  ...  ...  ...  ...  ...
75 -1.313469  100.0  0.0  0.0  1.0  0.0  1.0
76 -1.435558  101.0  0.0  0.0  1.0  0.0  0.0
77 -1.191381  101.0  1.0  0.0  0.0  0.0  1.0
78  1.209694   98.0  1.0  0.0  0.0  0.0  0.0
79  1.128302   98.0  0.0  0.0  1.0  0.0  1.0

[80 rows x 7 columns]

In [206]:
x_train_new.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64