In [163]:
import pandas as pd

In [164]:
df=pd.read_csv("orders.csv")

In [165]:
df.head(n=5)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [166]:
df.isnull().sum()

date          0
product_id    0
city_id       0
orders        0
dtype: int64

In [167]:
df.info() # date ----> object type ----> string

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [168]:
# converting string to DateTime type
df["date"]=pd.to_datetime(df["date"])

In [169]:
df

          date  product_id  city_id  orders
0   2019-12-10        5628       25       3
1   2018-08-15        3646       14     157
2   2018-10-23        1859       25       1
3   2019-08-17        7292       25       1
4   2019-01-06        4344       25       3
..         ...         ...      ...     ...
995 2018-10-08         255       13       1
996 2018-12-06        5521        7       1
997 2019-05-07         487       26      14
998 2019-03-03        1503       21       2
999 2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [170]:
df.info() # date column converted to DateTime data type.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [171]:
# extracting useful component
df["year"]=df["date"].dt.year
df["month"]=df["date"].dt.month
df["day"]=df["date"].dt.day
df["weekday"]=df["date"].dt.weekday
df["day_name"]=df["date"].dt.day_name()

In [172]:
df

,date,product_id,city_id,orders,year,month,day,weekday,day_name
0,2019-12-10,5628,25,3,2019,12,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,6,6,Sunday
...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,8,0,Monday
996,2018-12-06,5521,7,1,2018,12,6,3,Thursday
997,2019-05-07,487,26,14,2019,5,7,1,Tuesday
998,2019-03-03,1503,21,2,2019,3,3,6,Sunday
999,2019-10-15,6371,7,22,2019,10,15,1,Tuesday

Handling Time

In [173]:
df=pd.read_csv("messages.csv")

In [174]:
df

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [175]:
df["date"]=pd.to_datetime(df["date"])

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [ ]:
# extracting useful components

df["year"]=df["date"].dt.year
df["month"]=df["date"].dt.month
df["day"]=df["date"].dt.day
df["weekday"]=df["date"].dt.weekday
df["day_name"]=df["date"].dt.day_name()


df["time_12hr"] = pd.to_datetime(
    df["date"],
    format="%H:%M:%S"
).dt.strftime("%I:%M:%S %p") # 12 hour formate conversion ---> time_12hr will be object

df["hour"]=df["date"].dt.hour

In [178]:
df

,date,msg,year,month,day,weekday,day_name,time_12hr,hour
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15,6,Sunday,12:50:00 AM,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29,1,Tuesday,11:40:00 PM,23
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30,6,Sunday,12:21:00 AM,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28,4,Friday,12:31:00 AM,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26,5,Saturday,11:11:00 PM,23
...,...,...,...,...,...,...,...,...,...
995,2012-03-16 00:50:00,ПАРЕНЬ СДЕЛАЕТ МАССАЖ ЖЕНЩИНАМ -066-877-32-44,2012,3,16,4,Friday,12:50:00 AM,0
996,2014-01-23 23:14:00,сельский п 23 ищу девушку для отношений,2014,1,23,3,Thursday,11:14:00 PM,23
997,2012-10-15 23:37:00,Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...,2012,10,15,0,Monday,11:37:00 PM,23
998,2012-06-21 23:34:00,7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14,2012,6,21,3,Thursday,11:34:00 PM,23
999,2014-06-19 23:25:00,Парень поласкает девушке... т.0662035584,2014,6,19,3,Thursday,11:25:00 PM,23