In [84]:
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [85]:
import pandas as pd

In [86]:
df=pd.read_csv("customer.csv")

In [87]:
df.sample(n=10)

    age  gender   review education purchased
16   59    Male     Poor        UG       Yes
6    18    Male     Good    School        No
19   97    Male     Poor        PG       Yes
37   94    Male  Average        PG       Yes
15   75    Male     Poor        UG        No
4    16  Female  Average        UG        No
24   16  Female  Average        PG       Yes
7    60  Female     Poor    School       Yes
23   96  Female     Good    School        No
32   92    Male  Average        UG       Yes

In [88]:
# review , education ---> ordinal
# gender , purchased ---> nominal

In [89]:
# seperate input and output variables 
x=df[["review","education"]] # not take first two column as here i am learning only ordinal encoding for now.
y=df[["purchased"]]

In [90]:
x.sample()

   review education
19   Poor        PG

In [91]:
y.sample()

  purchased
0        No

In [92]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [93]:
# ordinal encoding ---> used for input variables
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])
columns=x_train.columns
x_train=encoder.fit_transform(x_train)
x_test=encoder.transform(x_test)

In [94]:
x_train=pd.DataFrame(data=x_train,columns=columns)

In [95]:
x_train

    review  education
0      1.0        1.0
1      1.0        0.0
2      2.0        0.0
3      2.0        2.0
4      0.0        0.0
5      2.0        0.0
6      0.0        2.0
7      1.0        2.0
8      0.0        1.0
9      2.0        1.0
10     2.0        1.0
11     2.0        1.0
12     1.0        1.0
13     2.0        0.0
14     0.0        1.0
15     1.0        0.0
16     1.0        1.0
17     0.0        1.0
18     0.0        0.0
19     2.0        0.0
20     1.0        2.0
21     0.0        2.0
22     2.0        2.0
23     0.0        1.0
24     0.0        0.0
25     2.0        2.0
26     0.0        2.0
27     0.0        2.0
28     0.0        0.0
29     2.0        0.0
30     0.0        2.0
31     0.0        2.0
32     1.0        0.0
33     2.0        1.0
34     0.0        0.0
35     1.0        1.0
36     2.0        2.0
37     1.0        0.0
38     2.0        1.0
39     2.0        1.0

In [96]:
# lable encoding --> used it for output variables
columns=y_train.columns
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

/home/sundramkumar/Learning ML/.venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/sundramkumar/Learning ML/.venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [100]:
y_train=pd.DataFrame(data=y_train,columns=columns)
y_test=pd.DataFrame(data=y_test,columns=columns)

In [101]:
y_train

    purchased
0           0
1           1
2           0
3           0
4           1
5           0
6           1
7           1
8           0
9           1
10          1
11          1
12          0
13          0
14          1
15          1
16          1
17          1
18          0
19          0
20          1
21          1
22          1
23          0
24          1
25          1
26          1
27          1
28          1
29          0
30          0
31          0
32          0
33          1
34          0
35          0
36          1
37          0
38          0
39          1