In [73]:
import pandas as pd

In [74]:
df=pd.read_csv("titanic.csv",usecols=["Cabin","Ticket"])

In [75]:
df

               Ticket Cabin
0           A/5 21171   NaN
1            PC 17599   C85
2    STON/O2. 3101282   NaN
3              113803  C123
4              373450   NaN
..                ...   ...
886            211536   NaN
887            112053   B42
888        W./C. 6607   NaN
889            111369  C148
890            370376   NaN

[891 rows x 2 columns]

In [76]:
df.isnull().sum()

Ticket      0
Cabin     687
dtype: int64

In [77]:
df["deck"]=df["Cabin"].str[0]

In [78]:
df

               Ticket Cabin deck
0           A/5 21171   NaN  NaN
1            PC 17599   C85    C
2    STON/O2. 3101282   NaN  NaN
3              113803  C123    C
4              373450   NaN  NaN
..                ...   ...  ...
886            211536   NaN  NaN
887            112053   B42    B
888        W./C. 6607   NaN  NaN
889            111369  C148    C
890            370376   NaN  NaN

[891 rows x 3 columns]

In [79]:
df["cabin_no"]=df["Cabin"].str[1:]

In [80]:
df

               Ticket Cabin deck cabin_no
0           A/5 21171   NaN  NaN      NaN
1            PC 17599   C85    C       85
2    STON/O2. 3101282   NaN  NaN      NaN
3              113803  C123    C      123
4              373450   NaN  NaN      NaN
..                ...   ...  ...      ...
886            211536   NaN  NaN      NaN
887            112053   B42    B       42
888        W./C. 6607   NaN  NaN      NaN
889            111369  C148    C      148
890            370376   NaN  NaN      NaN

[891 rows x 4 columns]

In [81]:
df["deck"]=df["deck"].fillna(value="Missing")

In [82]:
df

               Ticket Cabin     deck cabin_no
0           A/5 21171   NaN  Missing      NaN
1            PC 17599   C85        C       85
2    STON/O2. 3101282   NaN  Missing      NaN
3              113803  C123        C      123
4              373450   NaN  Missing      NaN
..                ...   ...      ...      ...
886            211536   NaN  Missing      NaN
887            112053   B42        B       42
888        W./C. 6607   NaN  Missing      NaN
889            111369  C148        C      148
890            370376   NaN  Missing      NaN

[891 rows x 4 columns]

In [83]:
df["cabin_no"] = df["cabin_no"].fillna(0)

In [84]:
df

               Ticket Cabin     deck cabin_no
0           A/5 21171   NaN  Missing        0
1            PC 17599   C85        C       85
2    STON/O2. 3101282   NaN  Missing        0
3              113803  C123        C      123
4              373450   NaN  Missing        0
..                ...   ...      ...      ...
886            211536   NaN  Missing        0
887            112053   B42        B       42
888        W./C. 6607   NaN  Missing        0
889            111369  C148        C      148
890            370376   NaN  Missing        0

[891 rows x 4 columns]

In [85]:
df["Ticket_Number"] = df["Ticket"].str.split().str[-1]

In [86]:
df["Ticket_Prefix"] = df["Ticket"].str.split().str[:-1].str.join(" ")

In [88]:
df.head()

             Ticket Cabin     deck cabin_no Ticket_Number Ticket_Prefix
0         A/5 21171   NaN  Missing        0         21171           A/5
1          PC 17599   C85        C       85         17599            PC
2  STON/O2. 3101282   NaN  Missing        0       3101282      STON/O2.
3            113803  C123        C      123        113803
4            373450   NaN  Missing        0        373450

In [89]:
df["Ticket_Prefix"] = df["Ticket_Prefix"].replace("", "NoPrefix")

In [90]:
df

               Ticket Cabin     deck cabin_no Ticket_Number Ticket_Prefix
0           A/5 21171   NaN  Missing        0         21171           A/5
1            PC 17599   C85        C       85         17599            PC
2    STON/O2. 3101282   NaN  Missing        0       3101282      STON/O2.
3              113803  C123        C      123        113803      NoPrefix
4              373450   NaN  Missing        0        373450      NoPrefix
..                ...   ...      ...      ...           ...           ...
886            211536   NaN  Missing        0        211536      NoPrefix
887            112053   B42        B       42        112053      NoPrefix
888        W./C. 6607   NaN  Missing        0          6607         W./C.
889            111369  C148        C      148        111369      NoPrefix
890            370376   NaN  Missing        0        370376      NoPrefix

[891 rows x 6 columns]