In [90]:
import pandas as pd

In [91]:
df=pd.read_csv("titanic.csv",usecols=["Age","Fare"])

In [92]:
df

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [93]:
df.isnull().sum()

Age     177
Fare      0
dtype: int64

In [94]:
# no of missing values in age
n=df["Age"].isnull().sum()

In [95]:
n

np.int64(177)

In [96]:
# create a copy
df["Age_imputed"]=df["Age"]

In [97]:
# Randomly sample from existing values
random_values =df['Age'].dropna().sample(
    n=df['Age'].isnull().sum(),
    random_state=42
).values


#filling
df.loc[
    df['Age_imputed'].isnull(),
    'Age_imputed'
] = random_values

In [98]:
df.sample(n=10)

      Age      Fare  Age_imputed
474  22.0    9.8375         22.0
482  50.0    8.0500         50.0
377  27.0  211.5000         27.0
593   NaN    7.7500         20.0
53   29.0   26.0000         29.0
502   NaN    7.6292         30.0
138  16.0    9.2167         16.0
266  16.0   39.6875         16.0
672  70.0   10.5000         70.0
589   NaN    8.0500         25.0

MISSING INDICATOR

In [99]:
df=pd.read_csv("titanic.csv",usecols=["Age","Fare"])

In [100]:
from sklearn.impute import SimpleImputer, MissingIndicator
# import pandas as pd

# # Indicator
# indicator = MissingIndicator(features='missing-only')
# age_indicator = indicator.fit_transform(df[['Age']])

# # Median Imputation
# imputer = SimpleImputer(strategy='median')
# df['Age'] = imputer.fit_transform(df[['Age']]).ravel()

# # Add indicator column
# df['Age_NA'] = age_indicator

In [101]:
df

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [102]:
# second method
si=SimpleImputer(add_indicator=True,strategy="mean")
df[["Age_Imputed","Age_NAN"]]=si.fit_transform(df[["Age"]])

In [104]:
df.sample(n=10)

      Age     Fare  Age_Imputed  Age_NAN
741  36.0  78.8500    36.000000      0.0
358   NaN   7.8792    29.699118      1.0
858  24.0  19.2583    24.000000      0.0
191  19.0  13.0000    19.000000      0.0
494  21.0   8.0500    21.000000      0.0
515  47.0  34.0208    47.000000      0.0
837   NaN   8.0500    29.699118      1.0
820  52.0  93.5000    52.000000      0.0
709   NaN  15.2458    29.699118      1.0
721  17.0   7.0542    17.000000      0.0