In [29]:
import pandas as pd

In [30]:
df=pd.read_csv('cars.csv')

In [31]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [32]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [33]:
df["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [34]:
# one hot encoding using panadas on fuel and owner column 
pd.get_dummies(data=df,columns=["fuel","owner"])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [35]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [36]:
# seperate input and output variables
x=df[['brand','km_driven','fuel','owner']] 
y=df[["selling_price"]]

In [37]:
x

        brand  km_driven    fuel                 owner
0      Maruti     145500  Diesel           First Owner
1       Skoda     120000  Diesel          Second Owner
2       Honda     140000  Petrol           Third Owner
3     Hyundai     127000  Diesel           First Owner
4      Maruti     120000  Petrol           First Owner
...       ...        ...     ...                   ...
8123  Hyundai     110000  Petrol           First Owner
8124  Hyundai     119000  Diesel  Fourth & Above Owner
8125   Maruti     120000  Diesel           First Owner
8126     Tata      25000  Diesel           First Owner
8127     Tata      25000  Diesel           First Owner

[8128 rows x 4 columns]

In [38]:
y

      selling_price
0            450000
1            370000
2            158000
3            225000
4            130000
...             ...
8123         320000
8124         135000
8125         382000
8126         290000
8127         290000

[8128 rows x 1 columns]

In [39]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [40]:
x_train

           brand  km_driven    fuel         owner
4293       Honda      50000  Petrol   First Owner
5904       Honda      50000  Diesel   First Owner
6989      Toyota      35000  Diesel  Second Owner
2487      Maruti      48000  Petrol  Second Owner
6013  Volkswagen       7949  Petrol   First Owner
...          ...        ...     ...           ...
5983     Renault      65000  Diesel  Second Owner
1226    Mahindra     110000  Petrol  Second Owner
1499     Hyundai     118000  Petrol   First Owner
834         Ford      80000  Diesel   First Owner
1456       Honda      80000  Petrol  Second Owner

[6502 rows x 4 columns]

In [41]:
x_test
columns=x_train.columns

In [51]:
# one hot encoding fuel and owner column using sklearn
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(drop="first",sparse_output=False) # sparse_output=false will give numpy array
x_train_new=encoder.fit_transform(df[["fuel","owner"]])

In [ ]:
x_train_new

numpy.ndarray

In [56]:
# joining brand ,km_driven with fuel and owner
import numpy as np
np.hstack((df[["brand","km_driven"]].values,x_train_new))

array([['Maruti', 145500, 1.0, ..., 0.0, 0.0, 0.0],
       ['Skoda', 120000, 1.0, ..., 1.0, 0.0, 0.0],
       ['Honda', 140000, 0.0, ..., 0.0, 0.0, 1.0],
       ...,
       ['Maruti', 120000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 25000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 25000, 1.0, ..., 0.0, 0.0, 0.0]],
      shape=(8128, 9), dtype=object)