In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("titanic.csv")

In [6]:
df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [7]:
df.sample(n=5)

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
293          294         0       3  ...   8.8500   NaN         S
468          469         0       3  ...   7.7250   NaN         Q
881          882         0       3  ...   7.8958   NaN         S
1              2         1       1  ...  71.2833   C85         C
495          496         0       3  ...  14.4583   NaN         C

[5 rows x 12 columns]

In [8]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [9]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [10]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [11]:
# sperate input and output variables
x=df[["Pclass","Sex","Age","SibSp"	,"Parch"	,"Fare"	,"Embarked"]]
y=df[["Survived"]]

In [12]:
x

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [13]:
y

     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]

In [14]:
#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [15]:
x_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
509       3    male  26.0      0      0   56.4958        S
339       1    male  45.0      0      0   35.5000        S
614       3    male  35.0      0      0    8.0500        S
874       2  female  28.0      1      0   24.0000        C
190       2  female  32.0      0      0   13.0000        S
..      ...     ...   ...    ...    ...       ...      ...
487       1    male  58.0      0      0   29.7000        C
182       3    male   9.0      4      2   31.3875        S
764       3    male  16.0      0      0    7.7750        S
856       1  female  45.0      1      1  164.8667        S
346       2  female  40.0      0      0   13.0000        S

[712 rows x 7 columns]

In [16]:
x_test

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
501       3  female  21.0      0      0    7.7500        Q
87        3    male   NaN      0      0    8.0500        S
865       2  female  42.0      0      0   13.0000        S
319       1  female  40.0      1      1  134.5000        C
10        3  female   4.0      1      1   16.7000        S
..      ...     ...   ...    ...    ...       ...      ...
576       2  female  34.0      0      0   13.0000        S
515       1    male  47.0      0      0   34.0208        S
0         3    male  22.0      1      0    7.2500        S
392       3    male  28.0      2      0    7.9250        S
853       1  female  16.0      0      1   39.4000        S

[179 rows x 7 columns]

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
# imputation transfomer
tnf1=ColumnTransformer(
    transformers=[
    ("age_imputer",SimpleImputer(strategy="mean"),["Age"]),
    ("embarked_imputer",SimpleImputer(strategy="most_frequent"),["Embarked"])
    ],
    remainder="passthrough"
)

In [18]:
# one hot encoding tranformer
from sklearn.preprocessing import OneHotEncoder
tnf2=ColumnTransformer(
    transformers=[
    ("sex_embarked_ohe",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),["Sex","Embarked"])
    ],
    remainder="passthrough"
)

In [19]:
# scaling
from sklearn.preprocessing import MinMaxScaler
tnf3=ColumnTransformer(
    transformers=[
        ("scaler",MinMaxScaler(),["Age","Fare"])
    ],
    remainder="passthrough"
)

In [20]:
#training model
from sklearn.tree import DecisionTreeClassifier
tnf4=DecisionTreeClassifier()

In [21]:
#creating pipeline
from sklearn.pipeline import Pipeline,make_pipeline
pipe=Pipeline(
    steps=[
        ('tnf1',tnf1),
        ('tnf2',tnf2),
        ('tnf3',tnf3),
        ('tnf4',tnf4), # model training ---> so use fit to train model later

    ]
)

In [22]:
#pipe.fit(x_train,y_train)
'''

NOTE 1 : Dont use ["Age","Embarked"] in column tranformer 
as after one hot encoding it wont work as ohe returns numpy array 

NOTE 2: dont create multiple tranformer as Your columns change position after every ColumnTransformer. 
meaning you cannt use indices as well like [2,6].

'''

'\n\nNOTE 1 : Dont use ["Age","Embarked"] in column tranformer \nas after one hot encoding it wont work as ohe returns numpy array \n\nNOTE 2: dont create multiple tranformer as Your columns change position after every ColumnTransformer. \nmeaning you cannt use indices as well like [2,6].\n\n'

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

preprocessor = ColumnTransformer([
    ("age_imputer",
     SimpleImputer(strategy="mean"),
     ["Age"]),

    ("embarked",
     Pipeline([
         ("imputer", SimpleImputer(strategy="most_frequent")),
         ("encoder", OneHotEncoder(handle_unknown="ignore"))
     ]),
     ["Embarked"]),

    ("sex",
     OneHotEncoder(handle_unknown="ignore",sparse_output=False),
     ["Sex"])
], remainder="passthrough")

pipe = Pipeline([
    ("preprocessor", preprocessor),
    ("model", DecisionTreeClassifier())
])

pipe.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('age_imputer',
                                                  SimpleImputer(), ['Age']),
                                                 ('embarked',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Embarked']),
                                                 ('sex',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Sex'])])),
                ('model', DecisionTreeClassifier())])

In [24]:
pipe.score(x_test,y_test) # return for classifier --> accuracy score and for regressor r square

0.7988826815642458

In [25]:
y_pred=pipe.predict(x_test)

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7988826815642458

In [27]:
pipe.named_steps

{'preprocessor': ColumnTransformer(remainder='passthrough',
                   transformers=[('age_imputer', SimpleImputer(), ['Age']),
                                 ('embarked',
                                  Pipeline(steps=[('imputer',
                                                   SimpleImputer(strategy='most_frequent')),
                                                  ('encoder',
                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                  ['Embarked']),
                                 ('sex',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  ['Sex'])]),
 'model': DecisionTreeClassifier()}

In [31]:
# cross validation
from sklearn.model_selection import cross_val_score
scores=cross_val_score(pipe,x_train,y_train,cv=5,scoring="accuracy")

In [ ]:
scores.mean()

np.float64(0.789421845759874)

In [ ]:
# Grid search using pipeline